### ISSUE TITLE
Please update your lib to make it GCC 10 compatilbe

### ISSUE THREAD

**Issue by misi** [digitalocean/prometheus-client-c#23]
See gcc 10 -fno-common update:
* https://gcc.gnu.org/gcc-10/porting_to.html

I use your lib in coturn and experience error with version gcc 10.
If I add extern before these vars works fine..
https://github.com/misi/prometheus-client-c

```
/usr/bin/ld: /tmp/cc8Yt5mw.o:/usr/include/prom_collector_registry.h:37: multiple definition of `PROM_COLLECTOR_REGISTRY_DEFAULT'; /tmp/ccL9shFy.o:/usr/include/prom_collector_registry.h:37: first defined here
/usr/bin/ld: /tmp/cc8Yt5mw.o:/usr/include/prom_histogram_buckets.h:44: multiple definition of `prom_histogram_default_buckets'; /tmp/ccL9shFy.o:/usr/include/prom_histogram_buckets.h:44: first defined here
/usr/bin/ld: /tmp/cc26uJhy.o:/usr/include/prom_collector_registry.h:37: multiple definition of `PROM_COLLECTOR_REGISTRY_DEFAULT'; /tmp/ccL9shFy.o:/usr/include/prom_collector_registry.h:37: first defined here
/usr/bin/ld: /tmp/cc26uJhy.o:/usr/include/prom_histogram_buckets.h:44: multiple definition of `prom_histogram_default_buckets'; /tmp/ccL9shFy.o:/usr/include/prom_histogram_buckets.h:44: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:136: bin/turnserver] Error 1
```
Please update your lib to work properly with gcc-10 

Many thanks for your help and cooperation in advance!

**Comment by miroswan** [comment]
@misi I've moved our builds to Github Actions so we get some more reliable building in the PR. I'm also adding gcc-10 to the build environment for each support OS:

```
########################################################################
1674
> prom: CMake Build Stage
1675
########################################################################
1676

1677
-- The C compiler identification is GNU 10.1.0
```

Would you mind letting me know what flags you passed to gcc so I can try to reproduce on my end?

**Comment by miroswan** [comment]
@misi Was able to reproduce. Merging @eyusupov's changes into my branch and testing now

**Comment by miroswan** [comment]
@misi I've merged some changes into master. If you checkout master and run `make test` a debian package will be generated. You can test the changes in your environment with this package.

**Comment by miroswan** [comment]
A new release has been cut with the aforementioned changes.
