### ISSUE TITLE
How to generate library in Windows？

### ISSUE THREAD

**Issue by cxyxiaoli** [digitalocean/prometheus-client-c#30]
Hello, how to generate a library that can be developed in Windows,such as prom.ib?I want to develop in Visual Studio2015.

**Comment by miroswan** [comment]
[Windows is not a currently supported operating system](https://github.com/digitalocean/prometheus-client-c#misc). We do not plan to support Windows in the future. However, we are open to contributions if there is a strong case for supporting it.

**Comment by cxyxiaoli** [comment]
Thanks for your help!
