### ISSUE TITLE
prom_*_new functions don't validate metrics names conform to specs

### ISSUE THREAD

**Issue by cfsmp3** [digitalocean/prometheus-client-c#31]
The specs for metrics name define the names must be [a-zA-Z_:][a-zA-Z0-9_:]*

but prom_histogram_new and friends don't validate, or any least the accept - (hyphen) which then results in this error from prometheus:

invalid metric type "gauges gauge"

(that happened with a call like this):
```
 prom_gauge_new("interleaver-gauges", "All internal interleaver gauges", 2,
                       (const char *[]){"instance_id", "metric"});
```

**Comment by miroswan** [comment]
That is correct. The regular expression you've shown does not except hyphens as a valid character.

**Comment by miroswan** [comment]
You may use underscores as an alternative.
