### ISSUE TITLE
How to use a Summary-type metric？

### ISSUE THREAD

**Issue by cxyxiaoli** [digitalocean/prometheus-client-c#32]
Hello, I need to use the summary-type metric, but I can only find the histogram-type in the source code.How do I use the summary metric？

**Comment by miroswan** [comment]
We do not support currently support the summary metric type as it requires additional computation in the client as opposed to the histogram. Thankfully Prometheus provides a (histogram_quantile)[https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile] function that allows you to query quantiles from your histograms. If you have a serious need for Summaries, please let us know and we'll consider adding support for it.

**Comment by cxyxiaoli** [comment]
Thanks for your reply!
